import path from "node:path";

async function createPres() {
  const mod = await import("pptxgenjs");
  const PptxGenJS = (mod as any).default ?? mod;
  return typeof PptxGenJS === "function" ? new PptxGenJS() : PptxGenJS;
}

export async function generatePptx(
  images: Array<{ buffer: Buffer; mimeType: string }>,
  width: number,
  height: number,
  outPath: string,
): Promise<string> {
  const pres = await createPres();

  const isLandscape = width >= height;
  const maxInch = 10;
  const wInch = isLandscape ? maxInch : maxInch * width / height;
  const hInch = isLandscape ? maxInch * height / width : maxInch;

  pres.defineLayout({ name: "SLIDESHOT", width: wInch, height: hInch });
  pres.layout = "SLIDESHOT";
  pres.author = "slideshot";
  pres.subject = "Generated by slideshot";

  for (const img of images) {
    const slide = pres.addSlide();
    const ext = img.mimeType === "image/png" ? "png" : "jpeg";
    slide.addImage({
      data: `image/${ext};base64,${img.buffer.toString("base64")}`,
      x: 0,
      y: 0,
      w: wInch,
      h: hInch,
    });
  }

  const fullPath = path.resolve(outPath);
  await pres.writeFile({ fileName: fullPath });
  return outPath;
}
